export { default as Dashboard } from '../Dashboard/Dashboard'
export { default as Customers } from '../Customers/Customers'
export { default as Products } from '../Products/Products'
export { default as Orders } from '../Orders/Orders'
export { default as Invoices } from '../Invoices/Invoices'
